# Generated by Django 2.0.2 on 2018-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reported_by', models.TextField(blank=True, null=True)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
